// <auto-generated />
namespace Mock3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OCForExamScore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OCForExamScore));
        
        string IMigrationMetadata.Id
        {
            get { return "202210141939582_OCForExamScore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
